In [2]:
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
import numpy as np


In [2]:
arr=np.arange(0,6,1)

In [3]:
arr

array([0, 1, 2, 3, 4, 5])

In [4]:
arr.dtype

dtype('int64')

In [5]:
#2.Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])

In [6]:
arr.dtype

dtype('float64')

In [5]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)


[1.+2.j 3.+4.j 5.+6.j]


In [ ]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.
arr=np.arange(0,6,1)

In [ ]:
arr1=arr.astype(np.float32)

In [ ]:
arr1

In [8]:
#5.Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
arr=np.random.rand(4)

In [9]:
arr

array([0.22986279, 0.66292949, 0.49852465, 0.09735398])

In [10]:
arr1=arr.astype(np.float32)

In [11]:
arr1

array([0.22986278, 0.6629295 , 0.49852467, 0.09735398], dtype=float32)

In [12]:
#6.Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and datatype
arr=np.random.randint(1,10,size=[2,3])

In [13]:
def array_attribute(arr):
    print("shape of the array",arr.shape)
    print("size of the array",arr.size)
    print("datatype of the array",arr.dtype)

In [14]:
array_attribute(arr)

shape of the array (2, 3)
size of the array 6
datatype of the array int64


In [15]:
#7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
arr=np.random.randint(1,10,size=[1,2,3])

In [16]:
def array_dimension(arr):
    print("The dimension of the array",arr.ndim)

In [17]:
array_dimension(arr)

The dimension of the array 3


In [18]:
#8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total sizein bytes.
arr=np.random.randint(1,10,size=[2,3])




In [19]:
def item_size(arr):
    print("item size",arr.itemsize)
    print("size in bytes",(arr.size*arr.itemsize))

In [20]:
item_size(arr)


item size 8
size in bytes 48


In [7]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
import numpy as np

def array_strides(arr):
    return arr.strides
arr=np.array([[1, 2, 3], [4, 5, 6]])
strides=array_strides(arr)
print(strides)

(24, 8)


In [8]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
import numpy as np

def shape_stride_relationship(arr):
    return arr.shape, arr.strides
example_array = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(example_array)
print("Shape:", shape)
print("Strides:", strides)

Shape: (2, 3)
Strides: (24, 8)
