In [2]:
import numpy as np


In [ ]:
#11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

def create_zeros_array(n):
    arr11=np.zeros(n,dtype=int)
    return arr11
    


In [15]:
n=int(input())

ar112=create_zeros_array(n)
print(ar112)

 3


[0 0 0]


In [16]:
#12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`
import numpy as np
def create_ones_matrix(row,column):
    ar12=np.ones((row,column),dtype=int)
    return ar12


In [17]:
row=int(input("Enter Row"))
column=int(input("Enter Column"))
ar122=create_ones_matrix(row,column)
print(ar122)

Enter Row 2
Enter Column 3


[[1 1 1]
 [1 1 1]]


In [19]:
#13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.
def generate_range_array(start,stop,step):
    arr13=np.arange(start,stop,step)
    return arr13

In [20]:
start=int(input("Enter Start"))
stop=int(input("Enter Stop"))
step=int(input("Enter Step"))
ar133=generate_range_array(start,stop,step)
print(ar133)

Enter Start 1
Enter Stop 11
Enter Step 1


[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
def generate_range_array(start,stop,step):
    arr13=np.linspace(start,stop,step)
    return arr13

In [14]:
start=int(input("Enter Start"))
stop=int(input("Enter Stop"))
step=int(input("Enter no of element"))
ar133=generate_range_array(start,stop,step)
print(ar133)

Enter Start 1
Enter Stop 15
Enter no of element 7


[ 1.          3.33333333  5.66666667  8.         10.33333333 12.66666667
 15.        ]


In [24]:
#15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.
def create_identity_matrix(n):
    arr14=np.eye(n,dtype=int)
    return arr14

In [25]:
n=int(input())

ar114=create_identity_matrix(n)
print(ar114)

 3


[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [27]:
#16. Write a function that takes a Python list and converts it into a NumPy array.
l=[1, 2, 3, 4, 5]
arr=np.array(l)

In [28]:
arr


array([1, 2, 3, 4, 5])

In [18]:
#17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
arr=np.array([1,2,3,4,5,6])
co=arr.view().reshape((3,2))

In [19]:
arr

array([1, 2, 3, 4, 5, 6])

In [20]:
co

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
"""The numpy.view method of NumPy forms a new view of an array with different data type 
or shape without copying the data. When implemented, it helps in changing the format  of the data and 
makes array reshaping more efficient. It does not change the original array which makes it better  to visualize 
array with different shape.Any change made in the original array is affected in the view as well"""

In [53]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr3=np.concatenate((arr1,arr2),axis=0)

In [29]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
#19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate
arr1=np.random.randint(1,5,(3,2))
arr2=np.random.randint(1,5,(3,1))

In [41]:
arr1

array([[1, 1],
       [3, 4],
       [1, 1]])

In [42]:
arr3=np.concatenate((arr1,arr2),axis=1)

In [43]:
arr2

array([[2],
       [3],
       [3]])

In [44]:
arr3

array([[1, 1, 2],
       [3, 4, 3],
       [1, 1, 3]])

In [48]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list.
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr3=np.vstack((arr1,arr2))

In [49]:
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])