In [5]:
import numpy as np
#21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
n=int(input("Enter lower limit"))
n1=int(input("Enter upper limit"))
s=int(input("Enter Step Size"))
np.arange(n,n1+1,s)

Enter lower limit 0
Enter upper limit 1
Enter Step Size 2


array([0])

In [6]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 
np.linspace(0,1,10)


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [6]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
np.logspace(1,1000,5,base=10)


array([1.00000000e+001, 5.62341325e+250,             inf,             inf,
                   inf])

In [9]:
#24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
np.random.randint(1,100,size=(5,3))

array([[81, 19, 51],
       [82, 92, 92],
       [53, 80, 20],
       [ 2, 90, 10],
       [ 4, 88, 32]])

In [1]:
#25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.
import pandas as pd
import numpy as np

def replace_negatives_with_zeros(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df


data = {'A': [1, -2, 3, -4, 5], 'B': [6, -7, 8, 9, -10]}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)


df = replace_negatives_with_zeros(df, 'A')
print("\nDataFrame after replacing negatives in column 'A' with zeros:")
print(df)

Original DataFrame:
   A   B
0  1   6
1 -2  -7
2  3   8
3 -4   9
4  5 -10

DataFrame after replacing negatives in column 'A' with zeros:
   A   B
0  1   6
1  0  -7
2  3   8
3  0   9
4  5 -10


In [11]:
#26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

In [13]:
#27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[1][2]


6

In [7]:
#28. Using boolean indexing, extract elements greater than 5 from the given NumPy array
arr = np.array([3, 8, 2, 10, 5, 7])
bool_arr=arr>5

In [8]:
bool_arr

array([False,  True, False,  True, False,  True])

In [9]:
arr[bool_arr]

array([ 8, 10,  7])

In [10]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

In [14]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_slice=arr_2d[0:2,1:3]

In [15]:
arr_slice

array([[2, 3],
       [5, 6]])