In [8]:
import numpy as np
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
arr=np.random.randint(1,50,(5,6))
arr1=np.array([[1,2],[2,3],[3,4]])




In [9]:
arr

array([[43,  3, 29,  4, 17, 13],
       [49, 10, 10, 42, 10,  4],
       [ 3, 21, 35, 40, 23, 47],
       [ 1, 14, 16, 18,  2, 44],
       [36, 27, 37,  1, 30, 48]])

In [23]:
for i in range (int(arr1.size/2)):
    print(arr[arr1[i][0]][arr1[i][1]])
  

10
40
2


In [36]:
#.32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
arr=np.arange(1,6,1)

In [37]:
arr

array([1, 2, 3, 4, 5])

In [38]:
bool_a=arr>3
bool_a

array([False, False, False,  True,  True])

In [39]:
arr[bool_a]

array([4, 5])

In [65]:
#33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
arr=np.random.randint(1,500,size=(2,2,3))
arr_i=np.array([0,0,1])
arr_j=np.array([0,1,1])
arr_k=np.array([0,1,2])

In [66]:
arr


array([[[249, 275,  22],
        [270,  16, 341]],

       [[279, 101, 237],
        [394, 104, 164]]])

In [67]:
for i in range(arr_i.size):
    print(arr[arr_i[i]][arr_j[i]][arr_k[i]])

249
16
164


In [ ]:
#34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.


In [24]:
arr=np.random.randint(1,50,(5,6))

In [25]:
arr

array([[24,  8, 20, 25, 17, 31],
       [16,  5, 35, 26, 10, 43],
       [41, 18, 39, 36, 24, 11],
       [39, 38, 38, 29,  8, 20],
       [ 7, 22, 32, 22, 16, 13]])

In [30]:
bool_a=(arr>4) & (arr%2==0)

In [31]:
bool_a

array([[ True,  True,  True, False, False, False],
       [ True, False, False,  True,  True, False],
       [False,  True, False,  True,  True, False],
       [False,  True,  True, False,  True,  True],
       [False,  True,  True,  True,  True, False]])

In [33]:
arr[bool_a]

array([24,  8, 20, 16, 26, 10, 18, 36, 24, 38, 38,  8, 20, 22, 32, 22, 16])

In [41]:
#35.Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

arr=np.random.randint(1,50,(4,5))
arr

array([[16, 29, 30, 31, 27],
       [49, 28,  3, 23,  2],
       [14, 30, 45, 31, 26],
       [29, 37, 33, 11, 21]])

In [43]:
arr_row=np.array([0,1,2])
arr_column=np.array([1,2,3])
for i in range (arr_row.size):
    print(arr[arr_row[i]][arr_column[i]])

29
3
31


In [23]:
#36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
arr=np.random.randint(1,500,size=(3,3))


In [24]:
arr


array([[ 45, 193, 324],
       [217, 268, 275],
       [122,  44, 119]])

In [25]:
arr1=arr+5

In [26]:
arr1

array([[ 50, 198, 329],
       [222, 273, 280],
       [127,  49, 124]])

In [47]:
#37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
arr=np.random.randint(1,500,size=(1,3))
arr1=np.random.randint(1,500,size=(3,4))

In [48]:
arr2=arr*arr1[0: ,0 ]

In [49]:
arr2

array([[ 43890, 109210,  45466]])

In [50]:
arr3=arr*arr1[0: ,1 ]

In [51]:
arr4=arr*arr1[0: ,1 ]

In [52]:
arr3

array([[  9842, 129748,  41886]])

In [42]:
arr4

array([[ 66450,   2952, 164379]])

In [53]:
np.vstack((arr2,arr3,arr4))

array([[ 43890, 109210,  45466],
       [  9842, 129748,  41886],
       [  9842, 129748,  41886]])

In [54]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
arr1=np.random.randint(1,500,size=(1,4))
arr2=np.random.randint(1,500,size=(4,3))

In [58]:
arr_a=arr1+arr2[0: ,0]

In [59]:
arr_b=arr1+arr2[0: ,1]

In [60]:
arr_c=arr1+arr2[0: ,2]

In [61]:
np.vstack((arr_a,arr_b,arr_c))

array([[457, 127, 502, 336],
       [440, 444, 736, 133],
       [385, 315, 721, 450]])

In [59]:
#39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
arr1=np.random.randint(1,50,size=(3,1))
arr2=np.random.randint(1,50,size=(1,3))

In [60]:
arr1+arr2

array([[34, 29, 15],
       [45, 40, 26],
       [42, 37, 23]])

In [2]:
#40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

import numpy as np


arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8],
                 [9, 10]])

arr2_reshaped = arr2[:, :, np.newaxis]


result = arr1 * arr2_reshaped

print(result)

[[[ 7 14 21]
  [32 40 48]]

 [[ 9 18 27]
  [40 50 60]]]
