In [2]:
import numpy as np
#41. Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr1=np.mean(arr,axis=0)


In [3]:
arr1

array([2.5, 3.5, 4.5])

In [4]:
#42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr1=np.max(arr,axis=1)

In [5]:
arr1

array([3, 6])

In [12]:
#43. For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr1=np.max(arr,axis=1)
indices=np.where(arr==arr1[0])
index=tuple(idx[0] for idx in indices)
indices1=np.where(arr==arr1[1])
index1=tuple(idx1[0] for idx1 in indices1)
print(index)
print(index1)

(0, 2)
(1, 2)


In [13]:
#44. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.sum(arr,axis=0)


array([5, 7, 9])

In [9]:
#45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])
all_even_columns = np.all(arr % 2 == 0, axis=0)
if np.all(all_even_columns):
    print("Yes all element in each colmn are even")
else:
    print("Not all elements in each column are even")


Not all elements in each column are even


In [6]:
#46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix
arr = np.array([1, 2, 3, 4, 5, 6])
m=int(input("enter m"))
n=int(input("enter n"))
arr.reshape((m,n))


enter m 2
enter n 3


array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
#47. Create a function that takes a matrix as input and returns the flattened array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.flatten(order="C")

array([1, 2, 3, 4, 5, 6])

In [24]:
#48. Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
array3=np.concatenate((array1,array2),axis=0
                     )

In [25]:
array3

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [26]:
#49. Create a function that splits an array into multiple sub-arrays along a specified axis.
arr= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.split(arr,3,axis=0)


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [13]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.
def pobo(arr,ind_i,v_i,i_d):
    arr1=np.insert(arr, ind_i, v_i)
    arr2=np.delete(arr1,i_d)
    print(arr1)
    print(arr2)
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
pobo(original_array,indices_to_insert,values_to_insert,indices_to_delete)

[ 1  2 10  3  4 11  5]
[ 1 10  4 11  5]
