In [3]:
import numpy as np

In [3]:
#51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.
arr1=np.arange(10)
arr2=np.random.randint(1,10,size=(1,10))
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr2

array([[7, 2, 5, 8, 1, 5, 6, 4, 3, 6]])

In [61]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr3=arr1+arr2

In [60]:
arr3

array([[ 7,  3,  7, 11,  5, 10, 12, 11, 11, 15]])

In [50]:
#52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.
arr1=np.arange(10)
arr2=np.arange(9,-1,-1)

In [51]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr2

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [55]:
arr3=arr2-arr1

In [56]:
arr3

array([ 9,  7,  5,  3,  1, -1, -3, -5, -7, -9])

In [26]:
#53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.
arr1=np.random.randint(5,size=(1,5))
arr2=np.arange(0,5)

In [27]:
arr1

array([[0, 0, 3, 2, 4]])

In [28]:
arr2

array([0, 1, 2, 3, 4])

In [29]:
arr2=arr1*arr2

In [30]:
arr2

array([[ 0,  0,  6,  6, 16]])

In [39]:
#54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.
arr2=np.random.randint(1,6,size=(1,5))
arr1=np.arange(2,11,2)
arr2=arr[arr<=5]

In [40]:
arr1

array([ 2,  4,  6,  8, 10])

In [41]:
arr2

array([4, 4, 4, 3, 2])

In [42]:
arr3=arr2/arr1

In [43]:
arr3

array([2.        , 1.        , 0.66666667, 0.375     , 0.2       ])

In [4]:
#55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
arr1=np.random.randint(1,6,size=(1,5))

In [5]:
arr1

array([[3, 5, 4, 1, 1]])

In [6]:
arr2=np.flip(arr1)

In [7]:
arr2

array([[1, 1, 4, 5, 3]])

In [8]:
arr3=np.power(arr1,arr2)

In [9]:
arr3

array([[  3,   5, 256,   1,   1]])

In [18]:
#56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

def char_counter(arr):
    char_count=np.char.count(arr,"lo")
    char_counter=char_count.sum(axis=0)
    print(char_counter)
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
char_counter(arr)

3


In [2]:
#57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
import numpy as np

def extract_uppercase(arr):
    
    result = np.array([''.join([char for char in string if char.isupper()]) for string in arr])
    return result


arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_characters = extract_uppercase(arr)
print(uppercase_characters)

['H' 'W' 'OAI' 'GPT']


In [16]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

def char_replace(arr):
    arr1=np.char.replace(arr,"le","bo")
    return arr1
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
arr2=char_replace(arr)
arr2

array(['appbo', 'banana', 'grape', 'pineappbo'], dtype='<U9')

In [21]:
# 59.Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
def concatenate_strings(arr1, arr2):
    concatenated_arr = np.char.add(arr1, arr2)
    return(concatenated_arr)
arr1=concatenate_strings(arr1,arr2)
arr1

array(['HelloOpen', 'WorldAI'], dtype='<U9')

In [24]:
#60. Write a function that finds the length of the longest string in a NumPy array.
def longest_length(arr):
     lengths = np.char.str_len(arr)
     max_length = np.max(lengths)
     return(max_length)   
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
max=longest_length(arr)
max


9