In [11]:
import numpy as np
#61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.
arr=np.random.randint(1,1000,(1,100))
arr

array([[858, 382, 843,  67, 459, 478, 639, 518, 910, 491, 818, 108, 172,
        374, 948, 526, 625,  23, 487,  60, 199, 504, 205,  66, 668, 511,
        546, 817, 470, 125, 354, 670, 170, 439, 145, 764, 830, 854, 455,
        969, 964, 113, 516, 944, 368,  62, 602, 232, 478,  45, 597, 330,
        664, 444, 593, 980, 837,  10,  19, 431, 336, 228, 912, 706, 850,
        772, 649,  73, 106, 958, 403, 621,  90, 125, 123,  41, 665, 205,
        225, 807, 785, 943, 459, 860, 820, 730, 927, 835,  13, 220,  84,
        404, 589, 611, 514, 583, 489, 403, 594, 163]])

In [21]:
print("mean",np.mean(arr),'\n',"median",np.median(arr),'\n',"variance",np.var(arr),'\n',"standard deviation" ,np.std(arr),'\n')


mean 486.97 
 median 490.0 
 variance 86131.6091 
 standard deviation 293.48187184219745 



In [25]:
#62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
arr=np.random.randint(1,100,(1,50))
print("25th percentile=",np.percentile(arr,25),'\n',"75th percentile=",np.percentile(arr,75))

25th percentile= 27.25 
 75th percentile= 64.0


In [32]:
#63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.
arr1=np.random.randint(1,100,(1,20))
arr2=np.random.randint(1,100,(1,20))
c_arr=np.corrcoef(arr1,arr2)
c_c=c_arr[0,1]
arr1

array([[75, 49, 68, 27, 21, 37,  5, 66, 44, 85, 95, 65, 80, 50, 66, 54,
        42, 56, 36, 80]])

In [33]:
arr2

array([[92, 95, 65, 66, 69, 66, 21, 96, 18, 26, 59, 20, 24,  2, 48, 46,
        30, 41, 39, 51]])

In [34]:
c_c

0.09144858180149942

In [38]:
#64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.
arr1=np.random.randint(1,50,(3,2))
arr2=np.random.randint(1,50,(2,3))
np.dot(arr1,arr2)

array([[ 777,  641,  431],
       [1506, 1234,  838],
       [ 357,  317,  191]])

In [44]:
#65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
arr=np.random.randint(1,1000,(1,50))
print("10th percentile=",np.percentile(arr,10))
print("50th percentile=",np.percentile(arr,50))
print("90th percentile=",np.percentile(arr,90))
print("first qartile=",np.percentile(arr,25))
print("third quartile=",np.percentile(arr,75))

10th percentile= 111.0
50th percentile= 550.5
90th percentile= 887.7
first qartile= 251.75
third quartile= 758.25


In [46]:
#66. Create a NumPy array of integers and find the index of a specific element.
arr=np.random.randint(1,40,(2,3))
arr

array([[24,  3, 15],
       [14, 26,  4]])

In [68]:
n=14
ind=np.where(arr==n)
index = tuple(idx[0] for idx in ind)
index

(1, 0)

In [77]:
#67. Generate a random NumPy array and sort it in ascending order.
arr=np.random.randint(1,50,(2,3))
sorted_arr=np.sort(arr.ravel()).reshape(2,3)
print("array =\n",arr)
print("sorted array =","\n",sorted_arr)

array =
 [[32 40 38]
 [ 2 44 38]]
sorted array = 
 [[ 2 32 38]
 [38 40 44]]


In [7]:
#68. Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])
arr1=arr[arr>20]

In [8]:
arr1

array([25, 42, 30])

In [4]:
#69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])
arr1=arr[arr%3==0]

In [5]:
arr1

array([12, 15])

In [9]:
#70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array
arr = np.array([10, 20, 30, 40, 50])
arr1=arr[arr>=20]
arr2=arr1[arr1<=40]

In [10]:
arr2

array([20, 30, 40])