In [18]:
import numpy as np

In [19]:
#71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
print("Byte order:", byte_order)



Byte order: =


In [ ]:
"""this = means the array has a byte order that matches the system's native byte order."""

In [21]:
#72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(True)
print("Array after byte swapping:", arr)

Array after byte swapping: [16777216 33554432 50331648]


In [22]:
#73. For the given NumPy array, swap its byte order without modifying the original array using`newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)
swapped_arr = arr.newbyteorder()
print("Original array:", arr)
print("Array with swapped byte order:", swapped_arr)

Original array: [1 2 3]
Array with swapped byte order: [16777216 33554432 50331648]


In [26]:
#74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)


if np.little_endian:
   
    swapped_arr = arr.newbyteorder('B')
else:
    
    swapped_arr = arr.newbyteorder('L')

print("Original array:", arr)
print("Array with swapped byte order:", swapped_arr)

Original array: [1 2 3]
Array with swapped byte order: [16777216 33554432 50331648]


In [27]:
#75.For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)
byte_order = arr.dtype.byteorder
if byte_order == '=':
    print("Byte order is native to the system. No swapping necessary.")
elif (byte_order == '<' and not np.little_endian) or (byte_order == '>' and np.little_endian):
    print("Byte order is different from the system's native byte order. Swapping is necessary.")
else:
    print("Byte order matches the system's native byte order. No swapping necessary.")

Byte order is native to the system. No swapping necessary.


In [29]:
#76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
arr1=np.random.randint(1,10,(2,3))
copy_arr=arr1.copy()
arr1

array([[8, 2, 9],
       [6, 3, 6]])

In [30]:
copy_arr

array([[8, 2, 9],
       [6, 3, 6]])

In [32]:
arr1[0][1]=20
arr1

array([[ 8, 20,  9],
       [ 6,  3,  6]])

In [33]:
copy_arr

array([[8, 2, 9],
       [6, 3, 6]])

In [ ]:
"""The change is not reflected in copy_arr as copy creates a seperate copy of the array unlike 
view where any change in the original array affects the view"""

In [35]:
#77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
arr=np.random.randint(1,100,(3,3))
arr

array([[16, 95, 83],
       [99, 26, 96],
       [27, 53, 45]])

In [40]:
view_slice=arr[0:2,1:3]
view_slice

array([[95, 83],
       [26, 96]])

In [42]:
view_slice[0][0]=32
view_slice

array([[32, 83],
       [26, 96]])

In [43]:
arr

array([[16, 32, 83],
       [99, 26, 96],
       [27, 53, 45]])

In [ ]:
"""as we see any change on the slice also affects the original array"""

In [66]:
#78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
array_a=np.random.randint(1,12,(4,3))
array_a

array([[9, 8, 1],
       [4, 1, 6],
       [1, 9, 7],
       [6, 3, 1]])

In [67]:
view_b=arr[0:3,1:3]
view_b

array([[10,  7],
       [ 9,  2],
       [ 8,  3]])

In [68]:
view_b=view_b+5
view_b

array([[15, 12],
       [14,  7],
       [13,  8]])

In [69]:
array_a

array([[9, 8, 1],
       [4, 1, 6],
       [1, 9, 7],
       [6, 3, 1]])

In [53]:
"""it does not affect the original array"""

'it does not affect the original array'

In [61]:
#79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if itreflects changes in the original `orig_array
orig_array=np.random.randint(1,9,(2,4))
reshaped_view=orig_array.view().reshape(4,2)
reshaped_view

array([[1, 4],
       [8, 5],
       [1, 7],
       [2, 3]])

In [62]:
orig_array


array([[1, 4, 8, 5],
       [1, 7, 2, 3]])

In [64]:
reshaped_view[0][1]=100
reshaped_view

array([[  1, 100],
       [  8,   5],
       [  1,   7],
       [  2,   3]])

In [65]:
orig_array

array([[  1, 100,   8,   5],
       [  1,   7,   2,   3]])

In [ ]:
"""any change in view is also reflected in the original array"""

In [73]:
#80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.
data=np.random.randint(1,12,(3,4))
data_copy=data.copy()[data>5]
data

array([[ 8, 11,  5,  9],
       [ 5, 10, 10,  5],
       [11,  7,  3,  3]])

In [74]:
data_copy

array([ 8, 11,  9, 10, 10, 11,  7])

In [76]:
data_copy[2]=300
data_copy

array([  8,  11, 300,  10,  10,  11,   7])

In [77]:
data

array([[ 8, 11,  5,  9],
       [ 5, 10, 10,  5],
       [11,  7,  3,  3]])

In [ ]:
"""any change in the copy is not reflected in the original array"""

In [2]:

#81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.
a=np.random.randint(1,1000,size=(3,2))
b=np.random.randint(1,1000,size=(3,2))
c=a+b
d=a-b

In [3]:
c

array([[1046,  840],
       [ 373,  703],
       [1583,  480]])

In [4]:
d

array([[ 384, -700],
       [ 133, -199],
       [ 145, -116]])

In [5]:
#82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
c=np.random.randint(1,50,size=(3,2))
d=np.random.randint(1,50,size=(2,4))

In [6]:
f=c@d

In [7]:
f

array([[1750, 1876, 2016, 1232],
       [1106,  602, 1260,  700],
       [1494,  564, 1696,  912]])

In [8]:
#83. Create a matrix `E` and find its transpose.
E=np.random.randint(1,50,size=(3,2))
F=E.T

In [9]:
E

array([[ 3, 39],
       [23,  7],
       [21, 48]])

In [10]:
F

array([[ 3, 23, 21],
       [39,  7, 48]])

In [11]:
#84. Generate a square matrix `F` and compute its determinant.
arr=np.random.randint(1,50,size=(4,4))
arr1=np.linalg.det(arr)


In [12]:
arr1

334379.9999999998

In [13]:
#85. Create a square matrix `G` and find its inverse.
G=np.random.randint(1,50,size=(4,4))
G1=np.linalg.inv(G)

In [14]:
G

array([[28, 31, 22, 19],
       [36, 15, 33, 11],
       [ 6, 45, 31, 35],
       [30, 19, 13, 15]])

In [15]:
G1

array([[ 1.50858005e-03,  9.42862531e-05, -1.58400905e-02,
         3.49801999e-02],
       [ 1.52662913e-01, -3.51014251e-02, -3.15320169e-02,
        -9.40572722e-02],
       [-7.83922847e-03,  4.41529054e-02,  1.08833275e-02,
        -4.78435387e-02],
       [-1.89596185e-01,  6.00738127e-03,  6.21885186e-02,
         1.57309879e-01]])